# Generated by Django 2.1.5 on 2019-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
